### PR TITLE
Turned regions into bounding boxes -(wait for feature toggle till merge)

### PR DESCRIPTION
**Pull request by Sean1572**
Allows users to create bounding boxes to annotate both time and frequency locations of bird calls in the audio files. 

This requires further testing to make sure it is working successfully. Merge this with a late-summer release.

### CODE REVIEW

**Comment by Sean1572** [comment]
TODO: fix bugs from rebase

**Comment by Sean1572** [comment]
Remake from scratch, not worth rebasing

**Comment by Sean1572** [comment]
Errors have been fixed
TODO:
- Update with recent wave surfer changes + lint
- Create system to toggle 2d-regions and 1d-region creation in region plugin system
- Wait for feature toggle to be merged in staging, pull from staging into this branch, and then combine 2d annotations into this system

**Comment by Sean1572** [comment]
Fixed conflict

**Review by nishantbalaji — APPROVED** [review]
LGTM!

**Comment by Sean1572** [comment]
Eh i'll merge it.

**Pull request merged**
