### PR TITLE
Componenterize Annotate

### LINKED ISSUE #137: Abstract Alert System
Make a general component that takes in values for alerts

### PR DESCRIPTION
**Pull request by Sean1572**
- Adds new components to make it easier to reorganize annotate
- Adds a general alert handler
- Turn features into separate components as well

Closes #137

### CODE REVIEW

**Comment by Sean1572** [comment]
Todo: Fix feature specific bugs

**Comment by Sean1572** [comment]
Todo: fix apply previous button bug

**Comment by Sean1572** [comment]
Bugs have been addressed, conflicts are dealt with. I think we are ready to merge in changes. 

Last thing I want to do is reduce the number of state variables in annotate.js, after that its ready to merge

**Review by nishantbalaji — APPROVED** [review]
I'm liking the functional components

**Pull request merged**
