### PR TITLE
[LARGE] Codebase Linting, Refactoring and Bugfixes

### LINKED ISSUE #7: Fix layout of labeling controls to take up less vertical space
Ideas
- Create 2 columns, one contains segment transition and the other contains the actual labeling

### LINKED ISSUE #83: Delete Label Category Bug
There is a conflict error when adding a new label after deleting a label. Thus a label is not getting deleted properly (ei, the label ID is shared by a previously deleted label).

- Test: Create Labels then delete them, if you can add additional labels, the issue is fixed.

### LINKED ISSUE #90: Mutli Annotation Support
Currently we have mostly worked our code to work well with a single label category, however projects should have the ability to have at least 2 label categories (Say a bird and bat label category).

TODO:
- Create 2 label categories in a test project
- Check to see if they both appear on the labeling page, fix if it doesn't
- Make sure all annotation data is sent to backend
- On backend save the data and make sure it appears in the json output
- Figure out a way to have the annotations of multiple categories appear on csv output (consult with jacob on this)

### LINKED ISSUE #105: Lint and clean frontend code
Issue to track Nishant's refractoring work

### LINKED ISSUE #112: CSV Output compatibility with PyHa
As of right now, the csv output names the labels "LABEL". For the sake of Kaleidoscope and PyHa compatibility, it needs to be "MANUAL ID"

### LINKED ISSUE #113: refactor annotate.js
break up the long file into multiple smaller ones

### LINKED ISSUE #126: README.md still references Audio_Labeling_System_AID
README.md on branch refactor commit 40a355d, line 23, references https://github.com/UCSD-E4E/Audio_Labeling_System_AID.git

Same file, line 30 also references the old repository name.

### LINKED ISSUE #127: README.md Docker instructions unclear
At commit 40a355d, README.md, line 38 - unclear what working directory to run `docker-compose -f docker-compose.dev.yml build` in.  This should probably be Pyrenote/audino.

### LINKED ISSUE #128: Similarity/duplication of contribution documentation
In branch refactor, Overview-Of-Code.MD and github_procedures.md are almost identical, but slightly different.
```
diff Overview-Of-Code.MD github_procedures.md 
3c3
< - create a branch of staging
---
> - create a branch of of staging
22,23c22,23
< Also don't push the file /audino/.env or rclone config files to the repo. 
< If this happens, no worries. Let the leads know so we can change the password.
---
> Also don't push the file /audino/.env to the repo. 
> If this happens, no worries. Lets the leads know so we can change the password.
\ No newline at end of file
```
As of commit 40a355d

### LINKED ISSUE #129: Lint Backend Python Code in Pep8
From @ntlhui : 

> Your code is missing a lot of documentation.  You are also completely not using Python type hints (https://docs.python.org/3.7/library/typing.html), which will help the linter do static analysis of your code.
> audino/backend/routes/__init__.py contains a lot of from ... import *.  This in general is very bad practice, as you end up overpopulating your namespace, and open yourself up to namespace conflicts down the road.  In addition, in general, it is frowned upon to have actual logic in the __init__.py files - these are merely there to initialize the package, and should not contain application logic.
> The activated linters note about 700 issues.  Some are due to my environment being funky, but that still leaves a couple hundred issues.

### LINKED ISSUE #134: Refactor Next/Previous Buttons into New Component
Move the code out of annotate.js and into its own file

### PR DESCRIPTION
**Pull request by nishantbalaji**
Closes #105 
Closes #113
Closes #134 
Closes #83 
Closes #112 
Closes #7
Closes #90
Closes #126 
Closes #127 
Closes #128 
Closes #129 

Changes: 
* Set up and enforced linting rules throughout the frontend codebase (#105)
* Updated code base with new linting rules and refactored to reduce code repetition:
      *  (#113) 
      * (#134)
* Fixed Label Category Bug (#83)
* Changes LABELS to MANUAL ID in csv output (#112) 
* Changes Next Button Layout (#7) 
* Fixes issues with mutli-select feature (#90)
* Addresses documentation issues:
     * (#126) 
     * (#127)  
     * (#128) 
* Linted backend python code in Pep8 (#129)

### CODE REVIEW

**Comment by Sean1572** [comment]
> Thanks!

No problem, Lets try to get this merged before we start getting users so we get these changes in

**Review by Sean1572 — APPROVED** [review]
Tested on Dev and Production build on local machine. All code changes seem stable enough for a main release

**Comment by Sean1572** [comment]
TODO:
- Create a proper overview of code documentation
- refactor next/previous buttons
- get more reviewers

**Review by vaibhavtiwari33 — APPROVED** [review]
Tested the dev build on my local machine. LGTM

**Pull request merged**
