### PR TITLE
Additional logging

### PR DESCRIPTION
**Pull request by Sean1572**
Provides a method to track user activity in the site. 

Still requires testing to make sure everything is working fine after merge

**I still need to add more logging outputs but I want to do that overtime rather than all in one pr.**

### CODE REVIEW

**Comment by Sean1572** [comment]
Most of these changes are just from the old refractor branch

**Comment by Sean1572** [comment]
Rebased branch with main

**Comment by Sean1572** [comment]
Still needs a system to retrieve logs

**Comment by Sean1572** [comment]
Todo: Rebase with annotate changes before putting logging messing everywhere

**Review by nishantbalaji — APPROVED** [review]
so far so good

**Pull request merged**
