### PR TITLE
Fixed clicking on spectrogram and not playing

### PR DESCRIPTION
**Pull request by Sean1572**
Test:
- Click on spectrogram
- Observe playback pauses correctly and spectrogram jumps to click
- playback should start at that point
- Also double check region creation

### CODE REVIEW

**Review by nishantbalaji — CHANGES_REQUESTED** [review]
spectrogram jumps, but doesnt play unless i press the play button, idk if this is intentional?

**Comment by Sean1572** [comment]
> spectrogram jumps, but doesnt play unless i press the play button, idk if this is intentional?

thats, a good question. Let me see what other video streaming platforms do and we can work from there

**Comment by Sean1572** [comment]
> > spectrogram jumps, but doesnt play unless i press the play button, idk if this is intentional?
> 
> thats, a good question. Let me see what other video streaming platforms do and we can work from there

Okay intended behavior is to not change playback mode, just jump to a new part of the playback

**Review by nishantbalaji — APPROVED** [review]
i got scared by a loud bird noise but it works!

**Pull request merged**
